In [1]:
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor

In [2]:
train_df = pd.read_csv(r"C:\potfolio\Advance_house_price_prediction\data\processed_data\processed_train.csv")
train_df.head()

,MSSubClass,LotFrontage,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterCond,...,Exterior_Wd Sdng_Stucco,Exterior_Wd Sdng_VinylSd,Exterior_Wd Sdng_Wd Sdng,Exterior_Wd Sdng_Wd Shng,Exterior_WdShing_HdBoard,Exterior_WdShing_Plywood,Exterior_WdShing_Stucco,Exterior_WdShing_Wd Sdng,Exterior_WdShing_Wd Shng,SalePrice
0,0.073375,-0.208034,-0.207142,0.290573,0.651479,-0.517200,1.050994,0.878668,0.510015,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.247699
1,-0.872563,0.409895,-0.091886,0.986242,-0.071836,2.179628,0.156734,-0.429577,-0.572835,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.109016
2,0.073375,-0.084449,0.073480,0.290573,0.651479,-0.517200,0.984752,0.830215,0.322174,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.317171
3,0.309859,-0.414011,-0.096897,0.506380,0.651479,-0.517200,-1.863632,-0.720298,-0.572835,-0.238112,...,-0.02618,-0.037037,-0.371427,12.697331,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,11.849405
4,0.073375,0.574676,0.375148,2.631741,1.374795,-0.517200,0.951632,0.733308,1.360826,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.429220

In [3]:
missing = {} 
length = len(train_df)
for col in train_df.columns:
    missing_val = train_df[col].isna().sum()
    missing[col] = (missing_val/length) * 100
missing

{'MSSubClass': 0.0,
 'LotFrontage': 17.73972602739726,
 'LotArea': 0.0,
 'Neighborhood': 0.0,
 'OverallQual': 0.0,
 'OverallCond': 0.0,
 'YearBuilt': 0.0,
 'YearRemodAdd': 0.0,
 'MasVnrArea': 0.547945205479452,
 'ExterCond': 0.0,
 'BsmtCond': 2.5342465753424657,
 'BsmtFinType1': 2.5342465753424657,
 'BsmtFinSF1': 0.0,
 'BsmtFinType2': 2.6027397260273974,
 'BsmtFinSF2': 0.0,
 'BsmtUnfSF': 0.0,
 'TotalBsmtSF': 0.0,
 '1stFlrSF': 0.0,
 '2ndFlrSF': 0.0,
 'LowQualFinSF': 0.0,
 'GrLivArea': 0.0,
 'BsmtFullBath': 0.0,
 'BsmtHalfBath': 0.0,
 'FullBath': 0.0,
 'HalfBath': 0.0,
 'BedroomAbvGr': 0.0,
 'KitchenAbvGr': 0.0,
 'TotRmsAbvGrd': 0.0,
 'Functional': 0.0,
 'Fireplaces': 0.0,
 'GarageYrBlt': 5.5479452054794525,
 'GarageCars': 0.0,
 'GarageArea': 0.0,
 'WoodDeckSF': 0.0,
 'OpenPorchSF': 0.0,
 'EnclosedPorch': 0.0,
 '3SsnPorch': 0.0,
 'ScreenPorch': 0.0,
 'PoolArea': 0.0,
 'MiscVal': 0.0,
 'MoSold': 0.0,
 'YrSold': 0.0,
 'MSZoning_FV': 0.0,
 'MSZoning_RH': 0.0,
 'MSZoning_RL': 0.0,
 'MSZoning_RM': 0.0,
 'Street_Pave': 0.0,
 'Alley_Pave': 0.0,
 'LotShape_IR2': 0.0,
 'LotShape_IR3': 0.0,
 'LotShape_Reg': 0.0,
 'LandContour_HLS': 0.0,
 'LandContour_Low': 0.0,
 'LandContour_Lvl': 0.0,
 'Utilities_NoSeWa': 0.0,
 'LotConfig_CulDSac': 0.0,
 'LotConfig_FR2': 0.0,
 'LotConfig_FR3': 0.0,
 'LotConfig_Inside': 0.0,
 'LandSlope_Mod': 0.0,
 'LandSlope_Sev': 0.0,
 'Condition1_Feedr': 0.0,
 'Condition1_Norm': 0.0,
 'Condition1_PosA': 0.0,
 'Condition1_PosN': 0.0,
 'Condition1_RRAe': 0.0,
 'Condition1_RRAn': 0.0,
 'Condition1_RRNe': 0.0,
 'Condition1_RRNn': 0.0,
 'Condition2_Feedr': 0.0,
 'Condition2_Norm': 0.0,
 'Condition2_PosA': 0.0,
 'Condition2_PosN': 0.0,
 'Condition2_RRAe': 0.0,
 'Condition2_RRAn': 0.0,
 'Condition2_RRNn': 0.0,
 'BldgType_2fmCon': 0.0,
 'BldgType_Duplex': 0.0,
 'BldgType_Twnhs': 0.0,
 'BldgType_TwnhsE': 0.0,
 'HouseStyle_1.5Unf': 0.0,
 'HouseStyle_1Story': 0.0,
 'HouseStyle_2.5Fin': 0.0,
 'HouseStyle_2.5Unf': 0.0,
 'HouseStyle_2Story': 0.0,
 'HouseStyle_SFoyer': 0.0,
 'HouseStyle_SLvl': 0.0,
 'RoofStyle_Gable': 0.0,
 'RoofStyle_Gambrel': 0.0,
 'RoofStyle_Hip': 0.0,
 'RoofStyle_Mansard': 0.0,
 'RoofStyle_Shed': 0.0,
 'RoofMatl_Other': 0.0,
 'RoofMatl_Tar&Grv': 0.0,
 'MasVnrType_BrkFace': 0.0,
 'MasVnrType_Stone': 0.0,
 'ExterQual_Fa': 0.0,
 'ExterQual_Gd': 0.0,
 'ExterQual_TA': 0.0,
 'Foundation_CBlock': 0.0,
 'Foundation_PConc': 0.0,
 'Foundation_Slab': 0.0,
 'Foundation_Stone': 0.0,
 'Foundation_Wood': 0.0,
 'BsmtQual_Fa': 0.0,
 'BsmtQual_Gd': 0.0,
 'BsmtQual_TA': 0.0,
 'BsmtExposure_Gd': 0.0,
 'BsmtExposure_Mn': 0.0,
 'BsmtExposure_No': 0.0,
 'Heating_GasA': 0.0,
 'Heating_GasW': 0.0,
 'Heating_Grav': 0.0,
 'Heating_OthW': 0.0,
 'Heating_Wall': 0.0,
 'HeatingQC_Fa': 0.0,
 'HeatingQC_Gd': 0.0,
 'HeatingQC_Po': 0.0,
 'HeatingQC_TA': 0.0,
 'CentralAir_Y': 0.0,
 'Electrical_FuseF': 0.0,
 'Electrical_FuseP': 0.0,
 'Electrical_Mix': 0.0,
 'Electrical_SBrkr': 0.0,
 'KitchenQual_Fa': 0.0,
 'KitchenQual_Gd': 0.0,
 'KitchenQual_TA': 0.0,
 'FireplaceQu_Fa': 0.0,
 'FireplaceQu_Gd': 0.0,
 'FireplaceQu_Po': 0.0,
 'FireplaceQu_TA': 0.0,
 'GarageType_Attchd': 0.0,
 'GarageType_Basment': 0.0,
 'GarageType_BuiltIn': 0.0,
 'GarageType_CarPort': 0.0,
 'GarageType_Detchd': 0.0,
 'GarageFinish_RFn': 0.0,
 'GarageFinish_Unf': 0.0,
 'GarageQual_Fa': 0.0,
 'GarageQual_Gd': 0.0,
 'GarageQual_Po': 0.0,
 'GarageQual_TA': 0.0,
 'GarageCond_Fa': 0.0,
 'GarageCond_Gd': 0.0,
 'GarageCond_Po': 0.0,
 'GarageCond_TA': 0.0,
 'PavedDrive_P': 0.0,
 'PavedDrive_Y': 0.0,
 'PoolQC_Fa': 0.0,
 'PoolQC_Gd': 0.0,
 'Fence_GdWo': 0.0,
 'Fence_MnPrv': 0.0,
 'Fence_MnWw': 0.0,
 'MiscFeature_Othr': 0.0,
 'MiscFeature_Shed': 0.0,
 'MiscFeature_TenC': 0.0,
 'SaleType_CWD': 0.0,
 'SaleType_Con': 0.0,
 'SaleType_ConLD': 0.0,
 'SaleType_ConLI': 0.0,
 'SaleType_ConLw': 0.0,
 'SaleType_New': 0.0,
 'SaleType_Oth': 0.0,
 'SaleType_WD': 0.0,
 'SaleCondition_AdjLand': 0.0,
 'SaleCondition_Alloca': 0.0,
 'SaleCondition_Family': 0.0,
 'SaleCondition_Normal': 0.0,
 'SaleCondition_Partial': 0.0,
 'Exterior_AsbShng_Plywood': 0.0,
 'Exterior_AsbShng_Stucco': 0.0,
 'Exterior_AsphShn_AsphShn': 0.0,
 'Exterior_BrkComm_Brk Cmn': 0.0,
 'Exterior_BrkFace_AsbShng': 0.0,
 'Exterior_BrkFace_BrkFace': 0.0,
 'Exterior_BrkFace_HdBoard': 0.0,
 'Exterior_BrkFace_Plywood': 0.0,
 'Exterior_BrkFace_Stone': 0.0,
 'Exterior_BrkFace_Stucco': 0.0,
 'Exterior_BrkFace_Wd Sdng': 0.0,
 'Exterior_BrkFace_Wd Shng': 0.0,
 'Exterior_CBlock_CBlock': 0.0,
 'Exterior_CemntBd_CmentBd': 0.0,
 'Exterior_CemntBd_Wd Sdng': 0.0,
 'Exterior_CemntBd_Wd Shng': 0.0,
 'Exterior_HdBoard_AsphShn': 0.0,
 'Exterior_HdBoard_HdBoard': 0.0,
 'Exterior_HdBoard_ImStucc': 0.0,
 'Exterior_HdBoard_MetalSd': 0.0,
 'Exterior_HdBoard_Plywood': 0.0,
 'Exterior_HdBoard_Wd Sdng': 0.0,
 'Exterior_HdBoard_Wd Shng': 0.0,
 'Exterior_ImStucc_ImStucc': 0.0,
 'Exterior_MetalSd_AsphShn': 0.0,
 'Exterior_MetalSd_HdBoard': 0.0,
 'Exterior_MetalSd_MetalSd': 0.0,
 'Exterior_MetalSd_Stucco': 0.0,
 'Exterior_MetalSd_Wd Sdng': 0.0,
 'Exterior_MetalSd_Wd Shng': 0.0,
 'Exterior_Plywood_Brk Cmn': 0.0,
 'Exterior_Plywood_HdBoard': 0.0,
 'Exterior_Plywood_ImStucc': 0.0,
 'Exterior_Plywood_Plywood': 0.0,
 'Exterior_Plywood_Wd Sdng': 0.0,
 'Exterior_Stone_HdBoard': 0.0,
 'Exterior_Stone_Stone': 0.0,
 'Exterior_Stucco_CmentBd': 0.0,
 'Exterior_Stucco_Stone': 0.0,
 'Exterior_Stucco_Stucco': 0.0,
 'Exterior_Stucco_Wd Shng': 0.0,
 'Exterior_VinylSd_AsbShng': 0.0,
 'Exterior_VinylSd_HdBoard': 0.0,
 'Exterior_VinylSd_ImStucc': 0.0,
 'Exterior_VinylSd_Other': 0.0,
 'Exterior_VinylSd_Plywood': 0.0,
 'Exterior_VinylSd_Stucco': 0.0,
 'Exterior_VinylSd_VinylSd': 0.0,
 'Exterior_VinylSd_Wd Sdng': 0.0,
 'Exterior_VinylSd_Wd Shng': 0.0,
 'Exterior_Wd Sdng_AsbShng': 0.0,
 'Exterior_Wd Sdng_BrkFace': 0.0,
 'Exterior_Wd Sdng_HdBoard': 0.0,
 'Exterior_Wd Sdng_ImStucc': 0.0,
 'Exterior_Wd Sdng_MetalSd': 0.0,
 'Exterior_Wd Sdng_Plywood': 0.0,
 'Exterior_Wd Sdng_Stone': 0.0,
 'Exterior_Wd Sdng_Stucco': 0.0,
 'Exterior_Wd Sdng_VinylSd': 0.0,
 'Exterior_Wd Sdng_Wd Sdng': 0.0,
 'Exterior_Wd Sdng_Wd Shng': 0.0,
 'Exterior_WdShing_HdBoard': 0.0,
 'Exterior_WdShing_Plywood': 0.0,
 'Exterior_WdShing_Stucco': 0.0,
 'Exterior_WdShing_Wd Sdng': 0.0,
 'Exterior_WdShing_Wd Shng': 0.0,
 'SalePrice': 0.0}

In [4]:
drop_col = []
for key, value in missing.items():
    if value > 0 :
        drop_col.append(key)
drop_col

['LotFrontage',
 'MasVnrArea',
 'BsmtCond',
 'BsmtFinType1',
 'BsmtFinType2',
 'GarageYrBlt']

In [5]:
for  col in drop_col:
    train_df[col] = train_df[col].fillna(train_df[col].mean())

train_df.head()

,MSSubClass,LotFrontage,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterCond,...,Exterior_Wd Sdng_Stucco,Exterior_Wd Sdng_VinylSd,Exterior_Wd Sdng_Wd Sdng,Exterior_Wd Sdng_Wd Shng,Exterior_WdShing_HdBoard,Exterior_WdShing_Plywood,Exterior_WdShing_Stucco,Exterior_WdShing_Wd Sdng,Exterior_WdShing_Wd Shng,SalePrice
0,0.073375,-0.208034,-0.207142,0.290573,0.651479,-0.517200,1.050994,0.878668,0.510015,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.247699
1,-0.872563,0.409895,-0.091886,0.986242,-0.071836,2.179628,0.156734,-0.429577,-0.572835,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.109016
2,0.073375,-0.084449,0.073480,0.290573,0.651479,-0.517200,0.984752,0.830215,0.322174,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.317171
3,0.309859,-0.414011,-0.096897,0.506380,0.651479,-0.517200,-1.863632,-0.720298,-0.572835,-0.238112,...,-0.02618,-0.037037,-0.371427,12.697331,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,11.849405
4,0.073375,0.574676,0.375148,2.631741,1.374795,-0.517200,0.951632,0.733308,1.360826,-0.238112,...,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854,12.429220

In [6]:
train_df.isna().sum()

MSSubClass                  0
LotFrontage                 0
LotArea                     0
Neighborhood                0
OverallQual                 0
                           ..
Exterior_WdShing_Plywood    0
Exterior_WdShing_Stucco     0
Exterior_WdShing_Wd Sdng    0
Exterior_WdShing_Wd Shng    0
SalePrice                   0
Length: 236, dtype: int64

In [7]:
train_df["SalePrice"]

0       12.247699
1       12.109016
2       12.317171
3       11.849405
4       12.429220
          ...
1455    12.072547
1456    12.254868
1457    12.493133
1458    11.864469
1459    11.901590
Name: SalePrice, Length: 1460, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

x = train_df.drop(columns= ["SalePrice"])
y = train_df["SalePrice"]

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=42)

gd = GradientBoostingRegressor(
    n_estimators=2000,
    learning_rate=0.01,
    max_depth=5,
    subsample=0.8,
    min_samples_split=12,
    random_state=42,
    criterion="squared_error"
)

In [9]:
gd.fit(x_train,y_train)

GradientBoostingRegressor(criterion='squared_error', learning_rate=0.01,
                          max_depth=5, min_samples_split=12, n_estimators=2000,
                          random_state=42, subsample=0.8)

In [10]:
y_pred = gd.predict(x_test)


import numpy as np 
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
y_pred_actual = np.expm1(y_pred)
y_test_actual = np.expm1(y_test)

print("RMSE:", np.sqrt(mean_squared_error(y_test_actual, y_pred_actual)))
print("MAE:", mean_absolute_error(y_test_actual, y_pred_actual))
print("R2:", r2_score(y_test_actual, y_pred_actual))

RMSE: 23380.994887180434
MAE: 14538.189469155133
R2: 0.9216589887378109

In [11]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(gd, x, y, cv=5, scoring="r2")
print("CV R2:", scores.mean())

CV R2: 0.9038078933865548

In [12]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=2500, max_depth=5, subsample=0.7,
    min_samples_split=12,
    random_state=42,learning_rate=0.03
)

xgb.fit(x_train,y_train)

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning: [17:04:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, min_samples_split=12,
             missing=nan, monotone_constraints=None, multi_strategy=None,
             n_estimators=2500, n_jobs=None, ...)

In [13]:
xgb_y_pred = xgb.predict(x_test)

actual_xgb_y_pred = np.expm1(xgb_y_pred)

print("RMSE:", np.sqrt(mean_squared_error(y_test_actual, actual_xgb_y_pred)))
print("MAE:", mean_absolute_error(y_test_actual, actual_xgb_y_pred))
print("R2:", r2_score(y_test_actual, actual_xgb_y_pred))

RMSE: 23006.584776489264
MAE: 14637.017337328769
R2: 0.9241479175816435

In [14]:
scores = cross_val_score(xgb, x, y, cv=5, scoring="r2")
print("CV R2:", scores.mean())

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning: [17:04:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning: [17:04:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning: [17:04:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning: [17:04:22] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning: [17:04:25] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

CV R2: 0.9033140695855358

In [15]:
residuals = y_test_actual - y_pred_actual

import plotly.graph_objects as go 
fig = go.Figure()


fig.add_trace(
    go.Scatter(
        x=y_pred_actual,
        y=residuals,
        mode="markers"
    )
)

fig.update_layout(
    title="Residual Plot",
    xaxis_title="Predicted Values",
    yaxis_title="Residuals"
)

fig.add_hline(y=0, line_dash="dash")

fig.show()

In [16]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=y_test_actual,
        y=y_pred_actual,
        mode="markers"
    )
)

fig.add_trace(
    go.Scatter(
        x=[y_test_actual.min(), y_test_actual.max()],
        y=[y_test_actual.min(), y_test_actual.max()],
        mode="lines"
    )
)

fig.update_layout(
    title="Actual vs Predicted",
    xaxis_title="Actual",
    yaxis_title="Predicted"
)

fig.show()

In [22]:
from sklearn.ensemble import HistGradientBoostingRegressor

hgb = HistGradientBoostingRegressor(
    learning_rate=0.01,
    max_depth=5,
    min_samples_leaf=3,
    max_iter=1500,
    random_state=42
)

hgb.fit(x_train, y_train)

HistGradientBoostingRegressor(learning_rate=0.01, max_depth=5, max_iter=1500,
                              min_samples_leaf=3, random_state=42)

In [23]:
hgb_y_pred = hgb.predict(x_test)

actual_hgb_y_pred = np.expm1(hgb_y_pred)

print("RMSE:", np.sqrt(mean_squared_error(y_test_actual, actual_hgb_y_pred)))
print("MAE:", mean_absolute_error(y_test_actual, actual_hgb_y_pred))
print("R2:", r2_score(y_test_actual, actual_hgb_y_pred))

RMSE: 22538.73580768871
MAE: 14774.87554526364
R2: 0.9272015210439922

In [45]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import Ridge, Lasso

stack_model = StackingRegressor(
    estimators=[
        ("gb", gd),
        ("xgb", xgb),
        ("hgb", hgb)
    ],
    final_estimator= Lasso(alpha=0.0010,max_iter=12000),
    cv=5,
    passthrough=False
)

stack_model.fit(x, y)

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:47:21] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:48:37] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:48:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:48:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:48:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:48:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

StackingRegressor(cv=5,
                  estimators=[('gb',
                               GradientBoostingRegressor(criterion='squared_error',
                                                         learning_rate=0.01,
                                                         max_depth=5,
                                                         min_samples_split=12,
                                                         n_estimators=2000,
                                                         random_state=42,
                                                         subsample=0.8)),
                              ('xgb',
                               XGBRegressor(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stoppi...
                                            max_delta_step=None, max_depth=5,
                                            max_leaves=None,
                                            min_child_weight=None,
                                            min_samples_split=12, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=2500, n_jobs=None, ...)),
                              ('hgb',
                               HistGradientBoostingRegressor(learning_rate=0.01,
                                                             max_depth=5,
                                                             max_iter=1500,
                                                             min_samples_leaf=3,
                                                             random_state=42))],
                  final_estimator=Lasso(alpha=0.001, max_iter=12000))

In [37]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(
    stack_model,
    x,
    y,
    cv=5,
    scoring="neg_root_mean_squared_error"
)

print("CV RMSE (log scale):", -scores.mean())

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:24:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:25:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:25:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:25:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:25:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:25:19] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:26:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:27:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:27:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:27:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:27:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:27:19] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:28:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:29:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:29:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:29:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:29:17] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:29:20] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:30:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:31:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:31:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:31:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:31:19] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:31:22] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:32:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:33:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:33:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:33:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:33:21] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:33:24] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

CV RMSE (log scale): 0.12315709002768774

In [41]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import Lasso

stack_model = StackingRegressor(
    estimators=[
        ("xgb", xgb),
        ("hgb", hgb)
    ],
    final_estimator=Lasso(alpha=0.001, max_iter=10000),
    cv=5,
    passthrough=False
)

stack_model.fit(x, y)

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:41:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:41:20] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:41:23] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:41:26] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:41:29] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:41:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

StackingRegressor(cv=5,
                  estimators=[('xgb',
                               XGBRegressor(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature_types=None,
                                            feature_weights=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_co...
                                            max_delta_step=None, max_depth=5,
                                            max_leaves=None,
                                            min_child_weight=None,
                                            min_samples_split=12, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=2500, n_jobs=None, ...)),
                              ('hgb',
                               HistGradientBoostingRegressor(learning_rate=0.01,
                                                             max_depth=5,
                                                             max_iter=1500,
                                                             min_samples_leaf=3,
                                                             random_state=42))],
                  final_estimator=Lasso(alpha=0.001, max_iter=10000))

In [39]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(
    stack_model,
    x,
    y,
    cv=5,
    scoring="neg_root_mean_squared_error"
)

print("CV RMSE (log scale):", -scores.mean())

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:34:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:17] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:35:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:36:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:37:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:35] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:38:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

CV RMSE (log scale): 0.1238574611133693

In [25]:
import joblib


def preprocess_test(df):

    df = df

    scaler = joblib.load("scaler.pkl")
    neigh_map = joblib.load("neighborhood_map.pkl")
    train_columns = joblib.load("train_columns.pkl")

    df.drop(columns=["Id"], inplace=True, errors="ignore")

    # Same encoding logic
    qual_map = {"Po":1,"Fa":2,"TA":3,"Gd":4,"Ex":5,"unknown":0}
    bsmt_map = {"Unf":0,"LwQ":1,"Rec":2,"BLQ":3,"ALQ":4,"GLQ":5,"unknown":-1}
    func_map = {"Sev":1,"Maj2":2,"Maj1":3,"Mod":4,"Min2":5,"Min1":6,"Typ":7}

    for col in ["ExterCond","BsmtCond"]:
        if col in df.columns:
            df[col] = df[col].map(qual_map)

    if "BsmtFinType1" in df.columns:
        df["BsmtFinType1"] = df["BsmtFinType1"].map(bsmt_map)

    if "BsmtFinType2" in df.columns:
        df["BsmtFinType2"] = df["BsmtFinType2"].map(bsmt_map)

    if "Functional" in df.columns:
        df["Functional"] = df["Functional"].map(func_map)

    # Target encoding using TRAIN map
    df["Neighborhood"] = df["Neighborhood"].map(neigh_map)

    # Rare handling
    freq = df["RoofMatl"].value_counts()
    rare = freq[freq < 10].index
    df["RoofMatl"] = df["RoofMatl"].replace(rare,"Other")

    # Combine exterior
    df["Exterior"] = df["Exterior1st"] + "_" + df["Exterior2nd"]
    df.drop(columns=["Exterior1st","Exterior2nd"], inplace=True)

    df = pd.get_dummies(df, drop_first=True)

    # Align columns with train
    df = df.reindex(columns=train_columns, fill_value=0)

    X_scaled = scaler.transform(df)

    test_df = pd.DataFrame(X_scaled, columns=train_columns)
    test_df.to_csv("processed_test.csv", index=False)

    return test_df

In [26]:
test = pd.read_csv(r"C:\potfolio\Advance_house_price_prediction\data\raw\test.csv")

test_ids = test["Id"].copy()   # SAVE ID FIRST

test_df = preprocess_test(test)

test_df.head()

,MSSubClass,LotFrontage,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterCond,...,Exterior_Wd Sdng_Stone,Exterior_Wd Sdng_Stucco,Exterior_Wd Sdng_VinylSd,Exterior_Wd Sdng_Wd Sdng,Exterior_Wd Sdng_Wd Shng,Exterior_WdShing_HdBoard,Exterior_WdShing_Plywood,Exterior_WdShing_Stucco,Exterior_WdShing_Wd Sdng,Exterior_WdShing_Wd Shng
0,-0.872563,0.409895,0.110763,-0.597937,-0.795151,0.381743,-0.340077,-1.156380,-0.572835,-0.238112,...,-0.02618,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854
1,-0.872563,0.451090,0.375850,-0.597937,-0.071836,0.381743,-0.439440,-1.301740,0.023838,-0.238112,...,-0.02618,-0.02618,-0.037037,2.692320,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854
2,0.073375,0.162723,0.332053,0.203437,-0.795151,-0.517200,0.852269,0.636400,-0.572835,-0.238112,...,-0.02618,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854
3,0.073375,0.327504,-0.054002,0.203437,-0.071836,0.381743,0.885390,0.636400,-0.462340,-0.238112,...,-0.02618,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854
4,1.492282,-1.114330,-0.552407,2.209018,1.374795,-0.517200,0.686666,0.345679,-0.572835,-0.238112,...,-0.02618,-0.02618,-0.037037,-0.371427,-0.078757,-0.037037,-0.058621,-0.02618,-0.02618,-0.10854

In [46]:
stack_pred = stack_model.predict(test_df)
final_pred = np.expm1(stack_pred)

submission = pd.DataFrame({
    "Id": test_ids,
    "SalePrice": final_pred
})

submission.to_csv("stack_submission_6.csv", index=False)

In [47]:
from sklearn.model_selection import cross_val_score

def evaluate(model):
    scores = cross_val_score(
        model,
        x,
        y,
        cv=5,
        scoring="neg_root_mean_squared_error"
    )
    return -scores.mean()

print("HGB:", evaluate(hgb))
print("XGB:", evaluate(xgb))
print("Stack:", evaluate(stack_model))

HGB: 0.1270427284224208

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:50:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:50:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:51:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:51:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:51:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

XGB: 0.12394267776741878

c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:51:25] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:52:28] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:52:31] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:52:34] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:52:37] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:52:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:53:26] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:54:29] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:54:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:54:35] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:54:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:54:41] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:55:28] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:56:30] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:56:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:56:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:56:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:56:42] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:57:29] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:58:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:58:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:58:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:58:42] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:58:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[17:59:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[18:00:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[18:00:42] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[18:00:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[18:00:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.


c:\Users\RITHIK KUMAR\.conda\envs\torch_env\Lib\site-packages\xgboost\training.py:199: UserWarning:

[18:00:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "min_samples_split" } are not used.

Stack: 0.12318276434733819

In [ ]:
y_pred_xgb = xgb.predict(test_df)
final_pred = np.expm1(y_pred_xgb)

submission = pd.DataFrame({
    "Id": test_ids,
    "SalePrice": final_pred
})

submission.to_csv("submission.csv", index=False)

In [ ]:
test_df.isna().sum().sort_values(ascending=False).head(20)

LotFrontage         227
GarageYrBlt          78
BsmtCond             45
BsmtFinType2         42
BsmtFinType1         42
MasVnrArea           15
Functional            2
BsmtHalfBath          2
BsmtFullBath          2
GarageCars            1
BsmtFinSF1            1
BsmtFinSF2            1
BsmtUnfSF             1
TotalBsmtSF           1
GarageArea            1
SaleType_ConLI        0
MiscFeature_Shed      0
SaleType_Oth          0
MiscFeature_TenC      0
SaleType_CWD          0
dtype: int64

In [28]:
test_df = test_df.fillna(0)

In [ ]:
y_pred_gd = gd.predict(test_df)
final_pred = np.expm1(y_pred_gd)

submission = pd.DataFrame({
    "Id": test_ids,
    "SalePrice": final_pred
})

# submission.to_csv("gd_submission.csv", index=False)